title : La Codeteca
description: 'La Codeteca'

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: https://la-codeteca.github.io/laCodeteca/
plugins: [jekyll-gist]
permalink: /:year/:month/:title.html
url: https://la-codeteca.github.io/laCodeteca/
